### ISSUE TITLE
Raising Exception: Bad Signature, When i am trying to get the data from encrypted field.

### ISSUE THREAD

**Issue by AnandMoorthy** [georgemarshall/django-cryptography#8] opened 2017-12-07 05:00 UTC
Hello all,

Encryption part in models going good, but when i start filtering data by a non-encrypted field i am geting bad signature exception. What am i missing here.

My Modal

```
class MyModal(models.Model):
    name = encrypt(models.CharField(max_length=50))
    area = models.CharField(max_length=50)

```

My Code:

```
from models import MyModal

def myFunc():
    data_list = MyModal.objects.filter(area='myarea')
    for data in data_list:
        print data.id
    return data.id
```

Is there anything i am missing?

**Comment by AnandMoorthy** [comment] 2017-12-12 07:58
If there any progress, please let me know.

**Comment by georgemarshall** [comment] 2017-12-13 08:38
I am currently unable to reproduce the issue. Could you please provide me with the message from the `BadSignature` exception?

Any other information that I should know about to reproduce this bug?

**Comment by georgemarshall** [comment] 2017-12-20 21:55
@AnandMoorthy I am closing this issue as I have been unable to reproduce the issue and lack sufficient information to do so. If further information is supplied I will come back to this issue and attempt to reproduce again.

**Closed by georgemarshall** 2017-12-20 21:55 UTC
Labels: bug

**Comment by thismatters** [comment] 2018-01-06 17:09
I think I was getting this as well because I had unencrypted data in a table that I later applied encryption to. When I started with a fresh database the error went away.

**Comment by veerendrapolepalli** [comment] 2018-03-30 20:21
yes i agree with @thismatters  , i need to remove all the data from the database and encrypt it then it started working with bad signature
